"""SYNTHETIC FIXTURES - not real tariff orders.

Generators for small PDFs that reproduce document-level failure modes from Section 6.1 that
Milestone 1 must inventory correctly: image-only pages mixed with born-digital pages, roman
and offset page labels, and rotated pages.  Every page carries the banner
``SYNTHETIC FIXTURE - NOT A TARIFF ORDER`` so no fixture can be mistaken for a source.

Fixtures are generated on demand (deterministic content) rather than committed as binaries.
"""

from __future__ import annotations

import re

import pymupdf

BANNER = "SYNTHETIC FIXTURE - NOT A TARIFF ORDER"

# Fixed timestamps keep the generated bytes deterministic: the same generator call must
# produce the same SHA-256 every time, or deduplication and golden-corpus tests would be
# testing the clock rather than the pipeline.
_FIXED_DATE = "D:20260101000000Z"


def _finalise(doc: pymupdf.Document, extra: dict[str, str] | None = None) -> bytes:
    meta = {
        "producer": "synthetic-fixture-generator",
        "creator": "tests/fixtures/synthetic_pdfs.py",
        "title": BANNER,
        "creationDate": _FIXED_DATE,
        "modDate": _FIXED_DATE,
        **(extra or {}),
    }
    doc.set_metadata(meta)
    data = doc.tobytes(garbage=3, deflate=True)
    doc.close()
    return _normalise_id(data)


# A PDF string is either hex `<...>` or a literal `(...)` with backslash escapes.  MuPDF
# writes the regenerated half of the /ID in whichever form is shorter, so roughly one file
# in fifty carries a literal.  Match both forms; the literal may contain any byte.
_PDF_STRING = rb"(?:<[0-9A-Fa-f]*>|\((?:\\.|[^\\)])*\))"
_ID_ARRAY = re.compile(rb"/ID\s*\[\s*" + _PDF_STRING + rb"\s*" + _PDF_STRING + rb"\s*\]", re.S)
_ZERO_ID = b"/ID[<" + b"0" * 32 + b"><" + b"0" * 32 + b">]"


def _normalise_id(data: bytes) -> bytes:
    """PyMuPDF regenerates the second half of the file /ID at save time, so two identical
    documents differ in a few bytes.  Zero both halves to make the generator byte-reproducible.
    The /ID lives in the trailer after the xref table, so a length change there leaves every
    offset valid; the re-open below proves it (a repaired document would mean an offset broke).
    Dedup, golden manifests and the ingest path key on SHA-256, so this must never silently
    fail: exactly one /ID array is expected."""
    out, n = _ID_ARRAY.subn(_ZERO_ID, data)
    if n != 1:
        raise AssertionError(f"expected one /ID array in the fixture PDF, found {n}")
    check = pymupdf.open(stream=out, filetype="pdf")
    try:
        if check.is_repaired:
            raise AssertionError("/ID normalisation broke the fixture PDF's xref")
    finally:
        check.close()
    return out


def mixed_text_and_image_pdf() -> bytes:
    """Six pages: 1-2 text with roman labels (i, ii); 3-4 text with decimal labels starting
    at 1 (printed label = index - 2); page 3 rotated 90; pages 5-6 image-only (no text layer)
    with decimal labels 3, 4.

    Failure modes exercised: scanned pages mixed with born-digital pages; printed labels that
    differ from PDF indices and use roman numerals; rotated pages inside a portrait document.
    """
    doc = pymupdf.open()
    for i in range(4):
        page = doc.new_page(width=595, height=842)
        page.insert_text((72, 72), BANNER, fontsize=10)
        page.insert_text((72, 120), f"Fixture text page {i + 1}. This page has a text layer.", fontsize=11)
        if i == 2:
            page.set_rotation(90)
    for i in range(2):
        page = doc.new_page(width=595, height=842)
        pix = pymupdf.Pixmap(pymupdf.csRGB, pymupdf.IRect(0, 0, 300, 120), 0)
        pix.clear_with(200 + i * 20)
        page.insert_image(pymupdf.Rect(72, 72, 372, 192), pixmap=pix)
    doc.set_page_labels(
        [
            {"startpage": 0, "prefix": "", "style": "r", "firstpagenum": 1},
            {"startpage": 2, "prefix": "", "style": "D", "firstpagenum": 1},
        ]
    )
    return _finalise(doc)


def text_only_pdf(pages: int = 3, seed: str = "A") -> bytes:
    doc = pymupdf.open()
    for i in range(pages):
        page = doc.new_page()
        page.insert_text((72, 72), BANNER, fontsize=10)
        page.insert_text((72, 120), f"Variant {seed} page {i + 1}", fontsize=11)
    return _finalise(doc, {"subject": f"variant {seed}"})


def _footer(page: pymupdf.Page, label: str, of: int | None = None) -> None:
    text = f"Page {label} of {of}" if of else f"Page {label}"
    page.insert_text((250, 820), text, fontsize=9)


def _ruled_table(page: pymupdf.Page, top: float, rows: int = 8, cols: int = 4, cell_h: float = 22) -> None:
    """Draw a genuine ruled table with text in every cell."""
    left, width = 60, 475
    col_w = width / cols
    for r in range(rows + 1):
        y = top + r * cell_h
        page.draw_line((left, y), (left + width, y), width=0.6)
    for c in range(cols + 1):
        x = left + c * col_w
        page.draw_line((x, top), (x, top + rows * cell_h), width=0.6)
    headers = ["Description", "Fixed Charge", "Energy Charge", "Slab"]
    for r in range(rows):
        for c in range(cols):
            txt = headers[c] if r == 0 else (f"Row {r} item" if c == 0 else f"{r}.{c}0")
            page.insert_text((left + c * col_w + 4, top + r * cell_h + 15), txt, fontsize=8)


def labelled_order_pdf() -> bytes:
    """Mimics the KERC/GERC page-label shape: three roman-numbered contents pages, then body
    pages whose printed label is `PDF index − 3`, each with a `Page N` footer, one ruled rate
    table page, one vector-drawn table page with no text layer, one image-only page, one blank
    page, and one page whose footer disagrees with the rule.

    Failure modes exercised: D5 (roman + offset labels, label conflicts), D8 (vector-drawn
    table with no text), D1 (image-only page), plus the `table`, `blank` and `annexure_cover`
    classes.  Twelve pages total.
    """
    doc = pymupdf.open()
    # 1-3: contents pages, roman labels i-iii, narrative text
    for i, label in enumerate(["i", "ii", "iii"]):
        page = doc.new_page(width=595, height=842)
        page.insert_text((72, 72), BANNER, fontsize=10)
        page.insert_text((72, 110), "CONTENTS" if i == 0 else "List of tables", fontsize=14)
        for k in range(14):
            page.insert_text(
                (72, 150 + k * 18),
                f"Chapter {k + 1} the commission shall determine the tariff for supply of electricity ...... {k + 4}",
                fontsize=10,
            )
        _footer(page, label)
    # 4: body page, printed 1 (offset -3), narrative
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(30):
        page.insert_text(
            (72, 120 + k * 18),
            "The Commission has considered the submissions of the petitioner and the objections "
            "received from the consumers regarding the proposed tariff.",
            fontsize=9,
        )
    _footer(page, "1")
    # 5: annexure cover, printed 2
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((150, 380), "ANNEXURE - I", fontsize=22)
    page.insert_text((120, 420), "RATE SCHEDULE FOR FY 2026-27", fontsize=16)
    _footer(page, "2")
    # 6: ruled rate table, printed 3
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((72, 100), "RATE SCHEDULE LMV-1", fontsize=12)
    _ruled_table(page, top=130, rows=14)
    _footer(page, "3")
    # 7: vector-drawn table with NO text layer (the KERC hazard), printed 4 but no footer
    page = doc.new_page(width=595, height=842)
    for r in range(20):
        for c in range(6):
            x, y = 60 + c * 80, 120 + r * 28
            page.draw_rect(pymupdf.Rect(x, y, x + 80, y + 28), width=0.5)
            # "text" drawn as tiny path strokes, not glyphs
            for k in range(6):
                page.draw_line((x + 6 + k * 10, y + 14), (x + 12 + k * 10, y + 14), width=1.2)
    # 8: image-only page, printed 5, no footer
    page = doc.new_page(width=595, height=842)
    pix = pymupdf.Pixmap(pymupdf.csRGB, pymupdf.IRect(0, 0, 500, 700), 0)
    pix.clear_with(230)
    page.insert_image(pymupdf.Rect(48, 60, 548, 780), pixmap=pix)
    # 9: blank
    doc.new_page(width=595, height=842)
    # 10: narrative, printed 7
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(28):
        page.insert_text(
            (72, 120 + k * 18),
            "General provisions applicable to all consumers: the regulatory discount of ten percent "
            "shall apply on fixed and energy charges.",
            fontsize=9,
        )
    _footer(page, "7")
    # 11: narrative whose footer CONFLICTS with the rule (says 99 instead of 8)
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(20):
        page.insert_text(
            (72, 120 + k * 18),
            "This page carries a wrong footer number to exercise the label conflict flag in the triage stage.",
            fontsize=9,
        )
    _footer(page, "99")
    # 12: narrative, printed 9
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(20):
        page.insert_text(
            (72, 120 + k * 18),
            "Final page of the synthetic order with the expected footer label according to the offset rule.",
            fontsize=9,
        )
    _footer(page, "9")
    return _finalise(doc, {"subject": "labelled order"})


def _aligned_table(
    page: pymupdf.Page, top: float, header: list[str], rows: list[tuple[str, ...]], xs: list[int]
) -> None:
    """An unruled, whitespace-aligned table: the KERC/UPERC text-table shape with no lines."""
    for c, x in enumerate(xs):
        page.insert_text((x, top), header[c], fontsize=9)
    for r, row in enumerate(rows):
        for c, x in enumerate(xs):
            page.insert_text((x, top + 20 * (r + 1)), row[c], fontsize=9)


def readers_and_headings_pdf() -> bytes:
    """Five pages exercising the second reader, agreement scoring, OCR and the heading
    inventory:

    1. KERC shape — `TARIFF SCHEDULE LT-1` printed twice (title, then caption) over an unruled,
       whitespace-aligned table: rulings find nothing, the text strategy must be used, and both
       readers should agree exactly.
    2. GERC shape — numbered clauses `1. RATE: RGP`, `1.1. FIXED CHARGES / MONTH`, narrative.
    3. UPERC shape — `RATE SCHEDULE LMV - 1` (spaced hyphen) over a ruled table; both readers agree.
    4. A scanned copy of page 3: the page rendered to a raster and inserted as a full-page image
       (`image_only`).  OCR must read the heading and the table words back.
    5. `Table 6-7 Approved distribution loss trajectory` caption over a ruled table, and a
       `CHAPTER - 6` heading.
    """
    doc = pymupdf.open()
    # 1
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((72, 110), "TARIFF SCHEDULE LT-1", fontsize=13)
    page.insert_text(
        (72, 140), "Applicable to Bhagya Jyothi / Kuteera Jyothi installations and private residences.", fontsize=9
    )
    page.insert_text((72, 170), "TARIFF SCHEDULE LT-1", fontsize=10)  # the caption repeat
    _aligned_table(
        page,
        200,
        ["Particulars", "FY2025-26", "FY2026-27", "FY2027-28"],
        [
            ("Fixed charge per KW / Month", "Rs.145/-", "Rs.150/-", "Rs.160/-"),
            ("Energy charge (Paise/Unit)", "580", "575", "575"),
            ("Minimum charge", "-", "-", "-"),
        ],
        [72, 260, 370, 480],
    )
    _footer(page, "1")
    # 2
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((72, 110), "1. RATE: RGP", fontsize=13)
    page.insert_text((72, 140), "1.1. FIXED CHARGES / MONTH", fontsize=11)
    page.insert_text((90, 165), "(a) Up to and including 2 kW ... Rs. 15/- per month", fontsize=10)
    page.insert_text((90, 185), "(b) Above 2 kW to 4 kW ... Rs. 25/- per month", fontsize=10)
    page.insert_text((72, 220), "PLUS", fontsize=11)
    page.insert_text((72, 250), "1.2. ENERGY CHARGES", fontsize=11)
    for k in range(18):
        page.insert_text(
            (72, 290 + k * 18),
            "The energy charges shall be payable by the consumer for the units consumed in the month.",
            fontsize=9,
        )
    _footer(page, "2")
    # 3
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    # Hyphen with spaces, not an en dash: PyMuPDF's base-14 font cannot encode U+2013 and
    # silently substitutes a middle dot in the text layer.  The en-dash spelling is covered by
    # the heading unit tests and, for real, by the NPCL order (hazard D.1).
    page.insert_text((72, 110), "RATE SCHEDULE LMV - 1", fontsize=13)
    page.insert_text((72, 135), "Domestic Light, Fan & Power", fontsize=10)
    _ruled_table(page, top=160, rows=8)
    _footer(page, "3")
    # 4: scan of page 3
    pix = doc[2].get_pixmap(dpi=150)
    page = doc.new_page(width=595, height=842)
    page.insert_image(page.rect, pixmap=pix)
    # 5
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((72, 100), "CHAPTER - 6", fontsize=12)
    page.insert_text((72, 130), "Table 6-7 Approved distribution loss trajectory", fontsize=10)
    _ruled_table(page, top=150, rows=5)
    _footer(page, "5")
    return _finalise(doc, {"subject": "readers and headings"})


def garbled_text_pdf() -> bytes:
    """A page whose text layer is present but useless: private-use codepoints and consonant
    soup, the symptom of a missing ToUnicode map (failure mode D2)."""
    doc = pymupdf.open()
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(25):
        page.insert_text(
            (72, 120 + k * 18),
            "\ue000\ue001\ue002 xqzvbn ptkrsd \ue010\ue011 wxqzb mnplk \ue020 zzxqw vbnmk",
            fontsize=10,
        )
    return _finalise(doc, {"subject": "garbled"})


def not_a_pdf() -> bytes:
    return b"%PDF-1.7\nthis is not really a pdf body\n"


def plain_text_bytes() -> bytes:
    return b"hello, this is not a pdf at all"


if __name__ == "__main__":
    import sys
    from pathlib import Path

    out = Path(sys.argv[1] if len(sys.argv) > 1 else "tests/fixtures/generated")
    out.mkdir(parents=True, exist_ok=True)
    (out / "SYNTHETIC_mixed_text_and_image.pdf").write_bytes(mixed_text_and_image_pdf())
    (out / "SYNTHETIC_text_only.pdf").write_bytes(text_only_pdf())
    (out / "SYNTHETIC_labelled_order.pdf").write_bytes(labelled_order_pdf())
    (out / "SYNTHETIC_garbled_text.pdf").write_bytes(garbled_text_pdf())
    (out / "SYNTHETIC_readers_and_headings.pdf").write_bytes(readers_and_headings_pdf())
    print(f"wrote synthetic fixtures to {out}")


# ------------------------------------------------------------------ Milestone 3a: whole-order layouts
#
# Three small synthetic orders that follow the *layout* of the supplied NPCL, KERC and GERC
# documents (Parts D, E, F) so that the localisation rules can be tested end to end: a
# contents page quoting every locator, ARR chapters with proposals and derived tables, network
# charge chapters, and the annexed schedule.  The numbers are meaningless placeholders.


def _lines(page: pymupdf.Page, y: float, lines: list[str], size: float = 9.5, step: float = 16) -> float:
    for ln in lines:
        page.insert_text((72, y), ln, fontsize=size)
        y += step
    return y


def _scan_page(doc: pymupdf.Document, text: str) -> None:
    """An image-only page: text rendered to a raster and inserted as a picture."""
    tmp = pymupdf.open()
    p = tmp.new_page(width=595, height=842)
    p.insert_text((72, 100), text, fontsize=12)
    pix = p.get_pixmap(dpi=100)
    page = doc.new_page(width=595, height=842)
    page.insert_image(page.rect, pixmap=pix)
    tmp.close()


def uperc_like_order_pdf(*, second_annexure: bool = False) -> bytes:
    """Fourteen pages in the NPCL shape (Part D): identity page labels (`Page N of 14`); a
    contents page quoting the annexure locators with dot leaders; Table 6-7 (loss trajectory);
    Chapter 7 proposals (the 20% TOD that was never approved); an existing/proposed table;
    Chapter 9 wheeling, losses, CSS and the zero additional surcharge; `12.1 ANNEXURE-I: RATE
    SCHEDULE` with general provisions (green tariff = provision 20) and three RATE SCHEDULE
    tables; `ANNEXURE-II` average billing rates (derived, not tariff); two scanned pages.

    ``second_annexure=True`` adds a second `ANNEXURE-I: RATE SCHEDULE` region separated from
    the first by the derived table: the ambiguity the rules must refuse to resolve alone."""
    doc = pymupdf.open()
    total = 16 if second_annexure else 14

    def new(label: int) -> pymupdf.Page:
        page = doc.new_page(width=595, height=842)
        page.insert_text((72, 60), BANNER, fontsize=9)
        _footer(page, str(label), total)
        return page

    # 1 cover
    p = new(1)
    _lines(
        p, 120, ["SYNTHETIC ELECTRICITY REGULATORY COMMISSION", "Tariff Order for FY 2026-27", "Licensee: NPCL"], 14, 24
    )
    # 2 contents
    p = new(2)
    _lines(
        p,
        110,
        [
            "CONTENTS",
            "CHAPTER 6 DISTRIBUTION LOSS ................................ 3",
            "CHAPTER 7 TARIFF PROPOSAL OF THE PETITIONER ................ 4",
            "CHAPTER 9 OPEN ACCESS CHARGES .............................. 6",
            "12.1 ANNEXURE-I: RATE SCHEDULE FOR FY 2026-27 .............. 8",
            "ANNEXURE-II: CATEGORY-WISE AVERAGE BILLING RATE ............ 12",
        ],
    )
    # 3 loss trajectory
    p = new(3)
    _lines(p, 110, ["CHAPTER - 6", "6.4 Distribution Loss", "Table 6-7 Approved distribution loss trajectory"], 11, 20)
    _ruled_table(p, 190, rows=4, cols=4)
    # 4 proposals in prose
    p = new(4)
    _lines(
        p,
        110,
        [
            "CHAPTER - 7",
            "7.2.3 The Petitioner has proposed to increase the TOD adjustment from 15% to 20% and the",
            "billable demand from 75% to 85% of contracted demand. The Commission has examined the",
            "proposal and does not approve it. The existing tariff shall continue to apply.",
        ],
    )
    # 5 existing / proposed table
    p = new(5)
    _lines(
        p,
        110,
        ["7.4 Existing Tariff and Proposed Tariff", "Table 7-3 Existing tariff and tariff proposed by the Petitioner"],
        11,
        20,
    )
    _aligned_table(
        p,
        170,
        ["Category", "Existing Tariff", "Proposed Tariff"],
        [("LMV-1", "6.50", "7.10"), ("LMV-2", "8.00", "8.60")],
        [72, 250, 400],
    )
    # 6 wheeling
    p = new(6)
    _lines(p, 110, ["CHAPTER - 9", "9.2 Wheeling Charges", "Table 9-5 Average Wheeling Charges (Rs/kWh)"], 11, 20)
    _ruled_table(p, 190, rows=3, cols=4)
    # 7 CSS, losses, additional surcharge
    p = new(7)
    _lines(
        p,
        110,
        [
            "9.3 Cross Subsidy Surcharge",
            "Table 9-11 Losses applicable for open access consumers",
            "9.4.7 The Commission approves the additional surcharge as zero for FY 2026-27.",
        ],
        11,
        20,
    )
    _ruled_table(p, 190, rows=5, cols=4)

    def annexure(start_label: int) -> None:
        pg = new(start_label)
        _lines(
            pg,
            110,
            [
                "12.1 ANNEXURE-I: RATE SCHEDULE FOR FY 2026-27",
                "(APPLICABLE FOR NPCL)",
                "A. GENERAL PROVISIONS",
                "20. Green Energy Tariff: Rs 0.34 per unit for HV and Rs 0.17 per unit for LMV categories",
                "21. A regulatory discount of 10% shall apply to fixed / demand and energy charges.",
            ],
            10.5,
            20,
        )
        pg = new(start_label + 1)
        _lines(
            pg,
            110,
            ["B. RETAIL TARIFFS FOR FINANCIAL YEAR 2026-27", "RATE SCHEDULE LMV - 1", "Domestic Light, Fan & Power"],
            11,
            20,
        )
        _ruled_table(pg, 190, rows=5, cols=4)
        pg = new(start_label + 2)
        _lines(pg, 110, ["RATE SCHEDULE LMV - 2", "Non-Domestic Light, Fan & Power"], 11, 20)
        _ruled_table(pg, 160, rows=5, cols=4)
        pg = new(start_label + 3)
        _lines(
            pg,
            110,
            ["RATE SCHEDULE HV-1", "Non-Industrial Bulk Loads", "TOD: Summer Months (April to September) (+) 15%"],
            11,
            20,
        )
        _ruled_table(pg, 180, rows=4, cols=4)

    annexure(8)  # pages 8-11
    # 12 derived table
    p = new(12)
    _lines(
        p,
        110,
        [
            "ANNEXURE-II: CATEGORY-WISE AVERAGE BILLING RATE (Rs/kWh)",
            "Note: The values are only for the purpose of fuel surcharge computation.",
        ],
        11,
        20,
    )
    _aligned_table(p, 170, ["Category", "ABR (Rs/kWh)"], [("LMV-1", "6.12"), ("LMV-9", "0.00")], [72, 300])
    if second_annexure:
        annexure(13)  # a second approved-schedule candidate after the derived table
        # (pages 13-16 replace the scans)
        return _finalise(doc)
    # 13-14 scans
    _scan_page(doc, "Scanned stamp page A")
    _scan_page(doc, "Scanned stamp page B")
    return _finalise(doc)


def kerc_like_order_pdf() -> bytes:
    """Twelve pages in the KERC shape (Part E): roman contents pages; Tables 6.2A/6.2B
    (existing and proposed, one per ESCOM); Table 6.3A (approved summary); a network-charges
    page; `ANNEXURE – 9` with `ELECTRICITY TARIFF - 2026`, the general terms, three TARIFF
    SCHEDULE pages (LT-1 printed twice, LT-4(a) with `-`, HT-1 with ToD); a scanned annexure.
    Printed labels: i, ii, then 1.. (index - 2)."""
    doc = pymupdf.open()

    def new(label: str, section: str | None = None) -> pymupdf.Page:
        page = doc.new_page(width=595, height=842)
        page.insert_text((72, 60), BANNER, fontsize=9)
        page.insert_text((72, 78), "Karnataka Synthetic Commission - Tariff Order 2025 - All ESCOMs", fontsize=8)
        page.insert_text((250, 820), f"{section + '   ' if section else ''}Page {label}", fontsize=9)
        return page

    p = new("i")
    _lines(
        p,
        110,
        [
            "CONTENTS",
            "Chapter - 6 : Tariff ......................... 1",
            "6.8 Tariff Charges ........................... 3",
            "Annexure - 9 ............................... 5",
        ],
    )
    p = new("ii")
    _lines(
        p,
        110,
        [
            "LIST OF TABLES",
            "Table 6.2A Existing and proposed charges - BESCOM ....... 1",
            "Table 6.3A Approved tariff FY2025-26 ......... 3",
        ],
    )
    for i, (label, esc) in enumerate((("1", "BESCOM"), ("2", "MESCOM"))):
        p = new(label, "Chapter - 6 : Tariff")
        _lines(p, 110, ["6.7 Proposed tariff", f"Table 6.2{'AB'[i]}: Existing and Proposed charges - {esc}"], 11, 20)
        _aligned_table(
            p,
            170,
            ["Category", "Existing Charges (#)", "Proposed FY2025-26", "Proposed FY2026-27"],
            [("LT-1", "Rs.130/-", "Rs.145/-", "Rs.150/-"), ("LT-2", "Rs.80/-", "Rs.90/-", "Rs.95/-")],
            [72, 200, 340, 460],
        )
        p.insert_text((72, 260), "# As approved in Tariff Order 2024 dated 28.02.2024", fontsize=8)
    p = new("3", "Chapter - 6 : Tariff")
    _lines(p, 110, ["6.8 Tariff Charges", "Table 6.3A Approved tariff for FY2025-26"], 11, 20)
    _aligned_table(
        p,
        170,
        [
            "Category",
            "Description",
            "Fixed Charges Billing Unit",
            "Fixed Charges (In Rupees)",
            "Energy Charges (Paise/Unit)",
        ],
        [("LT-1", "Bhagya Jyothi", "per KW", "145", "580")],
        [72, 140, 240, 360, 470],
    )
    p = new("4", "Chapter - 6 : Tariff")
    _lines(
        p,
        110,
        [
            "6.12 Wheeling Charges for BESCOM, MESCOM, CESC, HESCOM and GESCOM",
            "6.13 Cross Subsidy Surcharge",
            "6.13.6 Additional Surcharge shall not be levied until a fresh petition is filed.",
        ],
        11,
        20,
    )
    p = new("5", "ANNEXURE - 9")
    _lines(
        p,
        140,
        [
            "ANNEXURE - 9",
            "ELECTRICITY TARIFF - 2026",
            "K.E.R.C. ORDER DATED: 27th MARCH 2025",
            "BESCOM  MESCOM  CESC  HESCOM  GESCOM",
        ],
        13,
        26,
    )
    p = new("6", "ANNEXURE - 9")
    _lines(
        p,
        110,
        [
            "GENERAL TERMS AND CONDITIONS OF TARIFF (APPLICABLE TO BOTH HT AND LT)",
            "1. Applicability of tariff.",
            "3. Minimum charges.",
        ],
        10.5,
        20,
    )
    p = new("7", "ANNEXURE - 9")
    _lines(
        p, 110, ["TARIFF SCHEDULE LT-1", "Applicable to Bhagya Jyothi installations.", "TARIFF SCHEDULE LT-1"], 11, 20
    )
    _aligned_table(
        p,
        190,
        ["Particulars", "FY2025-26", "FY2026-27", "FY2027-28"],
        [
            ("Fixed charge per KW / Month", "Rs.145/-", "Rs.150/-", "Rs.160/-"),
            ("Energy charge", "580 paise", "590 paise", "600 paise"),
        ],
        [72, 260, 360, 460],
    )
    p = new("8", "ANNEXURE - 9")
    _lines(p, 110, ["TARIFF SCHEDULE LT-4(a)", "Irrigation pump sets up to 10 HP."], 11, 20)
    _aligned_table(
        p, 170, ["Particulars", "FY2025-26"], [("Fixed charge", "-"), ("Energy charge", "610 paise")], [72, 300]
    )
    p = new("9", "ANNEXURE - 9")
    _lines(p, 110, ["TARIFF SCHEDULE HT-1", "Time of Day tariff: July to November (monsoon period)"], 11, 20)
    _aligned_table(
        p, 170, ["Hours", "Adjustment"], [("22:00 to 06:00", "(-)100"), ("18:00 to 22:00", "(+)100")], [72, 300]
    )
    _scan_page(doc, "ANNEXURE 1 (scanned)")
    return _finalise(doc)


def gerc_like_order_pdf() -> bytes:
    """Eleven pages in the GERC/MGVCL shape (Part F): roman contents; Chapter 8 FPPAS formula;
    Chapter 9 network charges; Chapter 10 `Existing description / Modified description`
    amendment table; `ANNEXURE: TARIFF SCHEDULE` with GENERAL conditions and numbered
    `<n>. RATE: <CODE>` clauses joined by PLUS / ALTERNATIVELY; the last page continues the
    schedule with no heading at all."""
    doc = pymupdf.open()

    def new(label: str) -> pymupdf.Page:
        page = doc.new_page(width=595, height=842)
        page.insert_text((72, 60), BANNER, fontsize=9)
        page.insert_text(
            (72, 78), "Synthetic Gujarat Vij Company Limited / Determination of Tariff for FY 2026-27", fontsize=8
        )
        page.insert_text((250, 820), f"Page {label}", fontsize=9)
        return page

    p = new("i")
    _lines(
        p,
        110,
        [
            "CONTENTS",
            "Chapter 8 FPPAS ............................... 1",
            "Chapter 10 Amendments ......................... 3",
            "ANNEXURE: TARIFF SCHEDULE ..................... 4",
        ],
    )
    p = new("ii")
    _lines(p, 110, ["LIST OF TABLES", "Table 10-1 Existing description and modified description ..... 3"])
    p = new("1")
    _lines(
        p,
        110,
        [
            "CHAPTER 8",
            "8.1 Fuel and Power Purchase Price Adjustment (FPPAS)",
            "FPPAS (%) = (A + B) / C x 100, where projected PPC = 4.42 Rs/kWh",
        ],
        11,
        20,
    )
    p = new("2")
    _lines(
        p,
        110,
        [
            "CHAPTER 9",
            "9.2 Wheeling Charges",
            "9.3 Losses for open access",
            "9.4 Cross Subsidy Surcharge",
            "9.5 Additional surcharge under the methodology of 30.08.2022",
        ],
        11,
        20,
    )
    p = new("3")
    _lines(p, 110, ["CHAPTER 10", "Table 10-1 Amendments to the tariff schedule"], 11, 20)
    _aligned_table(
        p,
        170,
        ["Clause", "Existing description", "Modified description"],
        [("1.4", "ToU discount 11:00 to 15:00 hours", "ToU discount 11:00 to 17:00 hours")],
        [72, 160, 380],
    )
    p = new("4")
    _lines(
        p,
        110,
        [
            "ANNEXURE: TARIFF SCHEDULE",
            "TARIFF FOR SUPPLY OF ELECTRICITY AT LOW TENSION, HIGH TENSION, AND EXTRA HIGH TENSION",
            "Effective from 1st April, 2026",
            "GENERAL",
            "1. The figures are the rates payable by consumers of DGVCL, MGVCL, PGVCL and UGVCL.",
        ],
        10.5,
        20,
    )
    p = new("5")
    _lines(
        p,
        110,
        [
            "PART - I",
            "1. RATE: RGP",
            "1.1. FIXED CHARGES / MONTH",
            "(a) Up to and including 2 kW ... Rs. 15/- per month",
            "(b) Above 2 kW to 4 kW ... Rs. 25/- per month",
            "PLUS",
            "1.2. ENERGY CHARGES",
            "                       Post-Paid Energy Charge   Pre-paid Energy Charge",
            "(a) First 50 units      305 Paise per Unit        296 Paise per Unit",
        ],
        10,
        18,
    )
    p = new("6")
    _lines(
        p,
        110,
        [
            "8. RATE: AG",
            "8.1.1 HP BASED TARIFF ... Rs. 200 per HP per month",
            "ALTERNATIVELY",
            "8.1.2 METERED TARIFF ... Rs. 20 per HP plus 60 Paise per Unit",
        ],
        10,
        18,
    )
    p = new("7")
    _lines(
        p,
        110,
        [
            "PART - II",
            "11. RATE: HTP-1",
            "11.1. DEMAND CHARGE",
            "(a) For the first 500 kVA of billing demand ... Rs. 150/- per kVA per month",
            "11.3. TIME OF USE CHARGES ... 45 Paise per Unit",
        ],
        10,
        18,
    )
    p = new("8")
    _lines(
        p,
        110,
        ["17. RATE: HT ELECTRIC VEHICLE (EV) CHARGING STATIONS", "17.1. DEMAND CHARGE ... Rs. 25/- per kVA per month"],
        10,
        18,
    )
    p = new("9")
    _lines(
        p,
        110,
        [
            "(b) The billing demand shall be the highest of the actual maximum demand, 85% of the",
            "contract demand and 100 kVA.",
            "Power factor adjustment: penalty of 1% of the energy charge bill per 1% below 90%.",
        ],
        10,
        18,
    )
    return _finalise(doc)
