"""SYNTHETIC FIXTURES - not real tariff orders.

Generators for small PDFs that reproduce document-level failure modes from Section 6.1 that
Milestone 1 must inventory correctly: image-only pages mixed with born-digital pages, roman
and offset page labels, and rotated pages.  Every page carries the banner
``SYNTHETIC FIXTURE - NOT A TARIFF ORDER`` so no fixture can be mistaken for a source.

Fixtures are generated on demand (deterministic content) rather than committed as binaries.
"""

from __future__ import annotations

import re

import pymupdf

BANNER = "SYNTHETIC FIXTURE - NOT A TARIFF ORDER"

# Fixed timestamps keep the generated bytes deterministic: the same generator call must
# produce the same SHA-256 every time, or deduplication and golden-corpus tests would be
# testing the clock rather than the pipeline.
_FIXED_DATE = "D:20260101000000Z"


def _finalise(doc: pymupdf.Document, extra: dict[str, str] | None = None) -> bytes:
    meta = {
        "producer": "synthetic-fixture-generator",
        "creator": "tests/fixtures/synthetic_pdfs.py",
        "title": BANNER,
        "creationDate": _FIXED_DATE,
        "modDate": _FIXED_DATE,
        **(extra or {}),
    }
    doc.set_metadata(meta)
    data = doc.tobytes(garbage=3, deflate=True)
    doc.close()
    return _normalise_id(data)


# A PDF string is either hex `<...>` or a literal `(...)` with backslash escapes.  MuPDF
# writes the regenerated half of the /ID in whichever form is shorter, so roughly one file
# in fifty carries a literal.  Match both forms; the literal may contain any byte.
_PDF_STRING = rb"(?:<[0-9A-Fa-f]*>|\((?:\\.|[^\\)])*\))"
_ID_ARRAY = re.compile(rb"/ID\s*\[\s*" + _PDF_STRING + rb"\s*" + _PDF_STRING + rb"\s*\]", re.S)
_ZERO_ID = b"/ID[<" + b"0" * 32 + b"><" + b"0" * 32 + b">]"


def _normalise_id(data: bytes) -> bytes:
    """PyMuPDF regenerates the second half of the file /ID at save time, so two identical
    documents differ in a few bytes.  Zero both halves to make the generator byte-reproducible.
    The /ID lives in the trailer after the xref table, so a length change there leaves every
    offset valid; the re-open below proves it (a repaired document would mean an offset broke).
    Dedup, golden manifests and the ingest path key on SHA-256, so this must never silently
    fail: exactly one /ID array is expected."""
    out, n = _ID_ARRAY.subn(_ZERO_ID, data)
    if n != 1:
        raise AssertionError(f"expected one /ID array in the fixture PDF, found {n}")
    check = pymupdf.open(stream=out, filetype="pdf")
    try:
        if check.is_repaired:
            raise AssertionError("/ID normalisation broke the fixture PDF's xref")
    finally:
        check.close()
    return out


def mixed_text_and_image_pdf() -> bytes:
    """Six pages: 1-2 text with roman labels (i, ii); 3-4 text with decimal labels starting
    at 1 (printed label = index - 2); page 3 rotated 90; pages 5-6 image-only (no text layer)
    with decimal labels 3, 4.

    Failure modes exercised: scanned pages mixed with born-digital pages; printed labels that
    differ from PDF indices and use roman numerals; rotated pages inside a portrait document.
    """
    doc = pymupdf.open()
    for i in range(4):
        page = doc.new_page(width=595, height=842)
        page.insert_text((72, 72), BANNER, fontsize=10)
        page.insert_text((72, 120), f"Fixture text page {i + 1}. This page has a text layer.", fontsize=11)
        if i == 2:
            page.set_rotation(90)
    for i in range(2):
        page = doc.new_page(width=595, height=842)
        pix = pymupdf.Pixmap(pymupdf.csRGB, pymupdf.IRect(0, 0, 300, 120), 0)
        pix.clear_with(200 + i * 20)
        page.insert_image(pymupdf.Rect(72, 72, 372, 192), pixmap=pix)
    doc.set_page_labels(
        [
            {"startpage": 0, "prefix": "", "style": "r", "firstpagenum": 1},
            {"startpage": 2, "prefix": "", "style": "D", "firstpagenum": 1},
        ]
    )
    return _finalise(doc)


def text_only_pdf(pages: int = 3, seed: str = "A") -> bytes:
    doc = pymupdf.open()
    for i in range(pages):
        page = doc.new_page()
        page.insert_text((72, 72), BANNER, fontsize=10)
        page.insert_text((72, 120), f"Variant {seed} page {i + 1}", fontsize=11)
    return _finalise(doc, {"subject": f"variant {seed}"})


def _footer(page: pymupdf.Page, label: str, of: int | None = None) -> None:
    text = f"Page {label} of {of}" if of else f"Page {label}"
    page.insert_text((250, 820), text, fontsize=9)


def _ruled_table(page: pymupdf.Page, top: float, rows: int = 8, cols: int = 4, cell_h: float = 22) -> None:
    """Draw a genuine ruled table with text in every cell."""
    left, width = 60, 475
    col_w = width / cols
    for r in range(rows + 1):
        y = top + r * cell_h
        page.draw_line((left, y), (left + width, y), width=0.6)
    for c in range(cols + 1):
        x = left + c * col_w
        page.draw_line((x, top), (x, top + rows * cell_h), width=0.6)
    headers = ["Description", "Fixed Charge", "Energy Charge", "Slab"]
    for r in range(rows):
        for c in range(cols):
            txt = headers[c] if r == 0 else (f"Row {r} item" if c == 0 else f"{r}.{c}0")
            page.insert_text((left + c * col_w + 4, top + r * cell_h + 15), txt, fontsize=8)


def labelled_order_pdf() -> bytes:
    """Mimics the KERC/GERC page-label shape: three roman-numbered contents pages, then body
    pages whose printed label is `PDF index − 3`, each with a `Page N` footer, one ruled rate
    table page, one vector-drawn table page with no text layer, one image-only page, one blank
    page, and one page whose footer disagrees with the rule.

    Failure modes exercised: D5 (roman + offset labels, label conflicts), D8 (vector-drawn
    table with no text), D1 (image-only page), plus the `table`, `blank` and `annexure_cover`
    classes.  Twelve pages total.
    """
    doc = pymupdf.open()
    # 1-3: contents pages, roman labels i-iii, narrative text
    for i, label in enumerate(["i", "ii", "iii"]):
        page = doc.new_page(width=595, height=842)
        page.insert_text((72, 72), BANNER, fontsize=10)
        page.insert_text((72, 110), "CONTENTS" if i == 0 else "List of tables", fontsize=14)
        for k in range(14):
            page.insert_text(
                (72, 150 + k * 18),
                f"Chapter {k + 1} the commission shall determine the tariff for supply of electricity ...... {k + 4}",
                fontsize=10,
            )
        _footer(page, label)
    # 4: body page, printed 1 (offset -3), narrative
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(30):
        page.insert_text(
            (72, 120 + k * 18),
            "The Commission has considered the submissions of the petitioner and the objections "
            "received from the consumers regarding the proposed tariff.",
            fontsize=9,
        )
    _footer(page, "1")
    # 5: annexure cover, printed 2
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((150, 380), "ANNEXURE - I", fontsize=22)
    page.insert_text((120, 420), "RATE SCHEDULE FOR FY 2026-27", fontsize=16)
    _footer(page, "2")
    # 6: ruled rate table, printed 3
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((72, 100), "RATE SCHEDULE LMV-1", fontsize=12)
    _ruled_table(page, top=130, rows=14)
    _footer(page, "3")
    # 7: vector-drawn table with NO text layer (the KERC hazard), printed 4 but no footer
    page = doc.new_page(width=595, height=842)
    for r in range(20):
        for c in range(6):
            x, y = 60 + c * 80, 120 + r * 28
            page.draw_rect(pymupdf.Rect(x, y, x + 80, y + 28), width=0.5)
            # "text" drawn as tiny path strokes, not glyphs
            for k in range(6):
                page.draw_line((x + 6 + k * 10, y + 14), (x + 12 + k * 10, y + 14), width=1.2)
    # 8: image-only page, printed 5, no footer
    page = doc.new_page(width=595, height=842)
    pix = pymupdf.Pixmap(pymupdf.csRGB, pymupdf.IRect(0, 0, 500, 700), 0)
    pix.clear_with(230)
    page.insert_image(pymupdf.Rect(48, 60, 548, 780), pixmap=pix)
    # 9: blank
    doc.new_page(width=595, height=842)
    # 10: narrative, printed 7
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(28):
        page.insert_text(
            (72, 120 + k * 18),
            "General provisions applicable to all consumers: the regulatory discount of ten percent "
            "shall apply on fixed and energy charges.",
            fontsize=9,
        )
    _footer(page, "7")
    # 11: narrative whose footer CONFLICTS with the rule (says 99 instead of 8)
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(20):
        page.insert_text(
            (72, 120 + k * 18),
            "This page carries a wrong footer number to exercise the label conflict flag in the triage stage.",
            fontsize=9,
        )
    _footer(page, "99")
    # 12: narrative, printed 9
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(20):
        page.insert_text(
            (72, 120 + k * 18),
            "Final page of the synthetic order with the expected footer label according to the offset rule.",
            fontsize=9,
        )
    _footer(page, "9")
    return _finalise(doc, {"subject": "labelled order"})


def _aligned_table(
    page: pymupdf.Page, top: float, header: list[str], rows: list[tuple[str, ...]], xs: list[int]
) -> None:
    """An unruled, whitespace-aligned table: the KERC/UPERC text-table shape with no lines."""
    for c, x in enumerate(xs):
        page.insert_text((x, top), header[c], fontsize=9)
    for r, row in enumerate(rows):
        for c, x in enumerate(xs):
            page.insert_text((x, top + 20 * (r + 1)), row[c], fontsize=9)


def readers_and_headings_pdf() -> bytes:
    """Five pages exercising the second reader, agreement scoring, OCR and the heading
    inventory:

    1. KERC shape — `TARIFF SCHEDULE LT-1` printed twice (title, then caption) over an unruled,
       whitespace-aligned table: rulings find nothing, the text strategy must be used, and both
       readers should agree exactly.
    2. GERC shape — numbered clauses `1. RATE: RGP`, `1.1. FIXED CHARGES / MONTH`, narrative.
    3. UPERC shape — `RATE SCHEDULE LMV - 1` (spaced hyphen) over a ruled table; both readers agree.
    4. A scanned copy of page 3: the page rendered to a raster and inserted as a full-page image
       (`image_only`).  OCR must read the heading and the table words back.
    5. `Table 6-7 Approved distribution loss trajectory` caption over a ruled table, and a
       `CHAPTER - 6` heading.
    """
    doc = pymupdf.open()
    # 1
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((72, 110), "TARIFF SCHEDULE LT-1", fontsize=13)
    page.insert_text(
        (72, 140), "Applicable to Bhagya Jyothi / Kuteera Jyothi installations and private residences.", fontsize=9
    )
    page.insert_text((72, 170), "TARIFF SCHEDULE LT-1", fontsize=10)  # the caption repeat
    _aligned_table(
        page,
        200,
        ["Particulars", "FY2025-26", "FY2026-27", "FY2027-28"],
        [
            ("Fixed charge per KW / Month", "Rs.145/-", "Rs.150/-", "Rs.160/-"),
            ("Energy charge (Paise/Unit)", "580", "575", "575"),
            ("Minimum charge", "-", "-", "-"),
        ],
        [72, 260, 370, 480],
    )
    _footer(page, "1")
    # 2
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((72, 110), "1. RATE: RGP", fontsize=13)
    page.insert_text((72, 140), "1.1. FIXED CHARGES / MONTH", fontsize=11)
    page.insert_text((90, 165), "(a) Up to and including 2 kW ... Rs. 15/- per month", fontsize=10)
    page.insert_text((90, 185), "(b) Above 2 kW to 4 kW ... Rs. 25/- per month", fontsize=10)
    page.insert_text((72, 220), "PLUS", fontsize=11)
    page.insert_text((72, 250), "1.2. ENERGY CHARGES", fontsize=11)
    for k in range(18):
        page.insert_text(
            (72, 290 + k * 18),
            "The energy charges shall be payable by the consumer for the units consumed in the month.",
            fontsize=9,
        )
    _footer(page, "2")
    # 3
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    # Hyphen with spaces, not an en dash: PyMuPDF's base-14 font cannot encode U+2013 and
    # silently substitutes a middle dot in the text layer.  The en-dash spelling is covered by
    # the heading unit tests and, for real, by the NPCL order (hazard D.1).
    page.insert_text((72, 110), "RATE SCHEDULE LMV - 1", fontsize=13)
    page.insert_text((72, 135), "Domestic Light, Fan & Power", fontsize=10)
    _ruled_table(page, top=160, rows=8)
    _footer(page, "3")
    # 4: scan of page 3
    pix = doc[2].get_pixmap(dpi=150)
    page = doc.new_page(width=595, height=842)
    page.insert_image(page.rect, pixmap=pix)
    # 5
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    page.insert_text((72, 100), "CHAPTER - 6", fontsize=12)
    page.insert_text((72, 130), "Table 6-7 Approved distribution loss trajectory", fontsize=10)
    _ruled_table(page, top=150, rows=5)
    _footer(page, "5")
    return _finalise(doc, {"subject": "readers and headings"})


def garbled_text_pdf() -> bytes:
    """A page whose text layer is present but useless: private-use codepoints and consonant
    soup, the symptom of a missing ToUnicode map (failure mode D2)."""
    doc = pymupdf.open()
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), BANNER, fontsize=10)
    for k in range(25):
        page.insert_text(
            (72, 120 + k * 18),
            "\ue000\ue001\ue002 xqzvbn ptkrsd \ue010\ue011 wxqzb mnplk \ue020 zzxqw vbnmk",
            fontsize=10,
        )
    return _finalise(doc, {"subject": "garbled"})


def not_a_pdf() -> bytes:
    return b"%PDF-1.7\nthis is not really a pdf body\n"


def plain_text_bytes() -> bytes:
    return b"hello, this is not a pdf at all"


if __name__ == "__main__":
    import sys
    from pathlib import Path

    out = Path(sys.argv[1] if len(sys.argv) > 1 else "tests/fixtures/generated")
    out.mkdir(parents=True, exist_ok=True)
    (out / "SYNTHETIC_mixed_text_and_image.pdf").write_bytes(mixed_text_and_image_pdf())
    (out / "SYNTHETIC_text_only.pdf").write_bytes(text_only_pdf())
    (out / "SYNTHETIC_labelled_order.pdf").write_bytes(labelled_order_pdf())
    (out / "SYNTHETIC_garbled_text.pdf").write_bytes(garbled_text_pdf())
    (out / "SYNTHETIC_readers_and_headings.pdf").write_bytes(readers_and_headings_pdf())
    print(f"wrote synthetic fixtures to {out}")
